# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vboxuser/training-linux/TP7-CMake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vboxuser/training-linux/TP7-CMake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vboxuser/training-linux/TP7-CMake/CMakeFiles /home/vboxuser/training-linux/TP7-CMake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vboxuser/training-linux/TP7-CMake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calculatriceStat

# Build rule for target.
calculatriceStat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculatriceStat
.PHONY : calculatriceStat

# fast build rule for target.
calculatriceStat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatriceStat.dir/build.make CMakeFiles/calculatriceStat.dir/build
.PHONY : calculatriceStat/fast

#=============================================================================
# Target rules for targets named calculatriceDyn

# Build rule for target.
calculatriceDyn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calculatriceDyn
.PHONY : calculatriceDyn

# fast build rule for target.
calculatriceDyn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatriceDyn.dir/build.make CMakeFiles/calculatriceDyn.dir/build
.PHONY : calculatriceDyn/fast

#=============================================================================
# Target rules for targets named exe

# Build rule for target.
exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exe
.PHONY : exe

# fast build rule for target.
exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/build
.PHONY : exe/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

src/app/main.o: src/app/main.c.o
.PHONY : src/app/main.o

# target to build an object file
src/app/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/app/main.c.o
.PHONY : src/app/main.c.o

src/app/main.i: src/app/main.c.i
.PHONY : src/app/main.i

# target to preprocess a source file
src/app/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/app/main.c.i
.PHONY : src/app/main.c.i

src/app/main.s: src/app/main.c.s
.PHONY : src/app/main.s

# target to generate assembly for a file
src/app/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/app/main.c.s
.PHONY : src/app/main.c.s

src/lib/calculatriceDyn/calculatriceDyn.o: src/lib/calculatriceDyn/calculatriceDyn.c.o
.PHONY : src/lib/calculatriceDyn/calculatriceDyn.o

# target to build an object file
src/lib/calculatriceDyn/calculatriceDyn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatriceDyn.dir/build.make CMakeFiles/calculatriceDyn.dir/src/lib/calculatriceDyn/calculatriceDyn.c.o
.PHONY : src/lib/calculatriceDyn/calculatriceDyn.c.o

src/lib/calculatriceDyn/calculatriceDyn.i: src/lib/calculatriceDyn/calculatriceDyn.c.i
.PHONY : src/lib/calculatriceDyn/calculatriceDyn.i

# target to preprocess a source file
src/lib/calculatriceDyn/calculatriceDyn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatriceDyn.dir/build.make CMakeFiles/calculatriceDyn.dir/src/lib/calculatriceDyn/calculatriceDyn.c.i
.PHONY : src/lib/calculatriceDyn/calculatriceDyn.c.i

src/lib/calculatriceDyn/calculatriceDyn.s: src/lib/calculatriceDyn/calculatriceDyn.c.s
.PHONY : src/lib/calculatriceDyn/calculatriceDyn.s

# target to generate assembly for a file
src/lib/calculatriceDyn/calculatriceDyn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatriceDyn.dir/build.make CMakeFiles/calculatriceDyn.dir/src/lib/calculatriceDyn/calculatriceDyn.c.s
.PHONY : src/lib/calculatriceDyn/calculatriceDyn.c.s

src/lib/calculatriceStat/calculatriceStat.o: src/lib/calculatriceStat/calculatriceStat.c.o
.PHONY : src/lib/calculatriceStat/calculatriceStat.o

# target to build an object file
src/lib/calculatriceStat/calculatriceStat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatriceStat.dir/build.make CMakeFiles/calculatriceStat.dir/src/lib/calculatriceStat/calculatriceStat.c.o
.PHONY : src/lib/calculatriceStat/calculatriceStat.c.o

src/lib/calculatriceStat/calculatriceStat.i: src/lib/calculatriceStat/calculatriceStat.c.i
.PHONY : src/lib/calculatriceStat/calculatriceStat.i

# target to preprocess a source file
src/lib/calculatriceStat/calculatriceStat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatriceStat.dir/build.make CMakeFiles/calculatriceStat.dir/src/lib/calculatriceStat/calculatriceStat.c.i
.PHONY : src/lib/calculatriceStat/calculatriceStat.c.i

src/lib/calculatriceStat/calculatriceStat.s: src/lib/calculatriceStat/calculatriceStat.c.s
.PHONY : src/lib/calculatriceStat/calculatriceStat.s

# target to generate assembly for a file
src/lib/calculatriceStat/calculatriceStat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calculatriceStat.dir/build.make CMakeFiles/calculatriceStat.dir/src/lib/calculatriceStat/calculatriceStat.c.s
.PHONY : src/lib/calculatriceStat/calculatriceStat.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... run"
	@echo "... calculatriceDyn"
	@echo "... calculatriceStat"
	@echo "... exe"
	@echo "... src/app/main.o"
	@echo "... src/app/main.i"
	@echo "... src/app/main.s"
	@echo "... src/lib/calculatriceDyn/calculatriceDyn.o"
	@echo "... src/lib/calculatriceDyn/calculatriceDyn.i"
	@echo "... src/lib/calculatriceDyn/calculatriceDyn.s"
	@echo "... src/lib/calculatriceStat/calculatriceStat.o"
	@echo "... src/lib/calculatriceStat/calculatriceStat.i"
	@echo "... src/lib/calculatriceStat/calculatriceStat.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

